### ISSUE TITLE
is there LICENCE?

### ISSUE THREAD

**Issue by haniokasai** [Ogiwara-CostlierRain464/Csharp#1]
it seems https://github.com/Ogiwara-CostlierRain464/Csharp/tree/master/MiNETplugins/ServerList 's licence is not decided yet.

**Comment by Ogiwara-CostlierRain464** [comment]
特にないです

**Comment by haniokasai** [comment]
勝手に使っていい？

**Comment by Ogiwara-CostlierRain464** [comment]
構わないよ〜

**Comment by haniokasai** [comment]
ありがとうございます
